# run: conda env create --file environment.yml
name: phd_ph4-01_Downloader-BASE
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - ipython>=7.30
  - ipykernel>=6.4
  # Data download API
  - cdsapi>=0.5

  - numpy>=1.22
  - xarray>=0.21
  - pandas>=1.3
  # Xarray voluntary dependencies
  - dask
  - netCDF4
  - bottleneck


  # Cordex
  - py-cordex>=0.2
  - python-cdo>=1 # for dummy topography
  - pip

  # plotting
  - cartopy>=0.18
  - matplotlib>=3.5
  - seaborn>=0.11